### ISSUE TITLE
Log stack trace when error occurs in a promise

### ISSUE THREAD

**Issue by vlevit** [okfn/opendatacensus#657]
Currently we use `console.log.bind(console)` as a catch handler in promises. It logs the error message but not the the stack trace. This makes debugging harder. We should replace this handler with the one which would log the stack trace.

See discussion in pull request #649.

**Comment by kravets-levko** [comment]
I think, console.trace should be a good replacement for console.log as it prints something like this:
<pre>
Trace: Error
    at Object.<anonymous> (/var/www/okfn/opendatacensus/census/routes/index.js:12:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at start (/var/www/okfn/opendatacensus/census/app.js:21:16)
    at module.exports (/var/www/okfn/opendatacensus/node_modules/throng/lib/throng.js:6:32)
    at Object.<anonymous> (/var/www/okfn/opendatacensus/server.js:8:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
</pre>

**Comment by pwalsh** [comment]
fixed in develop
